language: rust

rust:
  - stable
  - nightly

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

before_script:
  - rustup component add rustfmt

matrix:
  include:
    - os: linux
      rust: nightly


script:
  - cargo fmt --all -- --check
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace --all-features
  - export CARGO_INCREMENTAL=0
#  - cargo doc --verbose --workspace --no-deps --document-private-items
  - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
  - cargo build --verbose $CARGO_OPTIONS
  - cargo test --verbose --all-features $CARGO_OPTIONS
  - |
    zip -0 ccov.zip `find . \( -name "YOUR_PROJECT_NAME*.gc*" \) -print`;
    ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
    bash <(curl -s https://codecov.io/bash) -f lcov.info;


notifications:
  email:
    on_success: never
    on_failure: never
