[package]
name = "desub-core"
version = "0.0.1"
authors = [ "Andrew Plaza <andrew.plaza@parity.io>" ]
edition = "2018"

[dependencies]
failure = "0.1.6"
codec = { version = "1.1.0", package = "parity-scale-codec" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
runtime-metadata = { git = "https://github.com/paritytech/substrate/", package = "frame-metadata", branch = "polkadot-master" }
runtime-version = { git = "https://github.com/paritytech/substrate/", package = "sp-version", branch = "polkadot-master" }
substrate-primitives = { git = "https://github.com/paritytech/substrate/", package = "sp-core", branch = "polkadot-master" }
derive_more = "0.99.2"

[dependencies.type-metadata]
git = "https://github.com/insipx/type-metadata"
branch = "insipx/deseralize-registry"
package = "type-metadata"
default-features = false
features = ["std", "derive"]

# [features]
# substrate = []
# polkadot = []
