[package]
name = "desub-core"
version = "0.0.1"
authors = [ "Andrew Plaza <andrew.plaza@parity.io>" ]
edition = "2018"

[dependencies]
failure = "0.1.6"
codec = { version = "1.1.0", package = "parity-scale-codec" }
codec411 = { version = "4.1.1", package = "parity-codec", features = ["derive"] } # for backwards compatibility with v 7
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

runtime-metadata-latest = { git = "https://github.com/paritytech/substrate/", package = "frame-metadata", branch = "polkadot-master" }
runtime-metadata09 = { git = "https://github.com/paritytech/substrate/", package = "frame-metadata", rev = "a512dcdd3931aa571c92c8550a0e079d5b27239a" }
runtime-metadata08 = { git = "https://github.com/paritytech/substrate/", package = "srml-metadata", rev = "ac11c330a95827211e1999781b5f691e72387c9e" }
runtime-metadata07 = { git = "https://github.com/paritytech/substrate/", package = "srml-metadata",  rev = "7c8bd73cef8c6afd60fec837d8f5e732a39a5615" } # meta version is before Kusama
# runtime-metadata06 = { git = "https://github.com/paritytech/substrate/", package = "srml-metadata",  rev = "c3be75da8daec396c763b692ed3d2d6a1d50f92a" } # not supported (yet)
# runtime-metadata05 = { git = "https://github.com/paritytech/substrate/", package = "srml-metadata",  rev = "b1c50952704c89079c8df41cea2be2ef0825a90d" } # not supported (yet)
# runtime-metadata04 = { git = "https://github.com/paritytech/substrate/", package = "srml-metadata",  rev = "19e533b3b01a0dab2d1238baaf223b348e4c24d4" } # not supported (yet)
# runtime-metadata03 = { git = "https://github.com/paritytech/substrate/", package = "srml-metadata",  rev = "0e6a407a13fbc5a5ad200645aed72bb8a8e528d7" } # not supported (yet)
# runtime-metadata02 = { git = "https://github.com/paritytech/substrate/", package = "srml-metadata",  rev = "6160ea5ac3bd7e1d1154b45a027ec9732ad59237" } # not supported (yet)
# runtime-metadata01 = { git = "https://github.com/paritytech/substrate/", package = "srml-metadata",  rev = "a29f214132a81f82e8b833f4d941b6d57680989f" } # not supported (yet)

runtime-version = { git = "https://github.com/paritytech/substrate/", package = "sp-version", branch = "polkadot-master" }
substrate-primitives = { git = "https://github.com/paritytech/substrate/", package = "sp-core", branch = "polkadot-master" }
derive_more = "0.99.2"

[dependencies.type-metadata]
git = "https://github.com/insipx/type-metadata"
branch = "insipx/deseralize-registry"
package = "type-metadata"
default-features = false
features = ["std", "derive"]

# [features]
# substrate = []
# polkadot = []
